version: "3.9"


services:
  pratico_api:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: pratico_api
    ports:
      - "5020:5020"
    volumes:
      - .:/app
    depends_on:
      - db
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
    networks:
      - android-network

  db:
    build: .docker/postgres
    container_name: db-android
    restart: always
    volumes:
      - data_postgres:/var/lib/postgressql/data
    environment:
      PGPORT: 5021
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5021:5021"
    expose:
      - "5021"
    networks:
      - android-network

networks:
  android-network:
    driver: bridge

volumes:
  data_postgres: {}

